<section class="rounded-lg border border-gray-200 bg-white p-6 shadow-sm">
    <div class="grid grid-cols-1 gap-5 md:grid-cols-2">
        <div><label for="code" class="block text-sm font-medium text-gray-700">Kode <span class="field-requirement is-required" aria-label="Wajib diisi">*</span></label><input id="code" name="code" value="{{ old('code', $shift->code) }}" required class="mt-2 block w-full rounded-md border border-gray-300 px-3 py-2.5 text-sm shadow-xs outline-none focus:border-primary focus:ring-2 focus:ring-primary/20">@error('code')<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror</div>
        <div><label for="name" class="block text-sm font-medium text-gray-700">Nama Shift <span class="field-requirement is-required" aria-label="Wajib diisi">*</span></label><input id="name" name="name" value="{{ old('name', $shift->name) }}" required class="mt-2 block w-full rounded-md border border-gray-300 px-3 py-2.5 text-sm shadow-xs outline-none focus:border-primary focus:ring-2 focus:ring-primary/20">@error('name')<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror</div>
        <div><label for="start_time" class="block text-sm font-medium text-gray-700">Jam Mulai <span class="field-requirement is-required" aria-label="Wajib diisi">*</span></label><input id="start_time" name="start_time" type="time" value="{{ old('start_time', $shift->start_time ? str($shift->start_time)->substr(0, 5) : '') }}" required class="mt-2 block w-full rounded-md border border-gray-300 px-3 py-2.5 text-sm shadow-xs outline-none focus:border-primary focus:ring-2 focus:ring-primary/20">@error('start_time')<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror</div>
        <div><label for="end_time" class="block text-sm font-medium text-gray-700">Jam Selesai <span class="field-requirement is-required" aria-label="Wajib diisi">*</span></label><input id="end_time" name="end_time" type="time" value="{{ old('end_time', $shift->end_time ? str($shift->end_time)->substr(0, 5) : '') }}" required class="mt-2 block w-full rounded-md border border-gray-300 px-3 py-2.5 text-sm shadow-xs outline-none focus:border-primary focus:ring-2 focus:ring-primary/20">@error('end_time')<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror</div>
        <div><label for="break_minutes" class="block text-sm font-medium text-gray-700">Istirahat (menit) <span class="field-requirement is-required" aria-label="Wajib diisi">*</span></label><input id="break_minutes" name="break_minutes" type="number" min="0" max="480" value="{{ old('break_minutes', $shift->break_minutes ?? 60) }}" required class="mt-2 block w-full rounded-md border border-gray-300 px-3 py-2.5 text-sm shadow-xs outline-none focus:border-primary focus:ring-2 focus:ring-primary/20">@error('break_minutes')<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror</div>
        <div><label for="late_tolerance_minutes" class="block text-sm font-medium text-gray-700">Toleransi Telat (menit) <span class="field-requirement is-required" aria-label="Wajib diisi">*</span></label><input id="late_tolerance_minutes" name="late_tolerance_minutes" type="number" min="0" max="240" value="{{ old('late_tolerance_minutes', $shift->late_tolerance_minutes ?? 0) }}" required class="mt-2 block w-full rounded-md border border-gray-300 px-3 py-2.5 text-sm shadow-xs outline-none focus:border-primary focus:ring-2 focus:ring-primary/20"><p class="mt-2 text-xs text-gray-500">Masuk dalam rentang ini masih dihitung tepat waktu.</p>@error('late_tolerance_minutes')<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror</div>
        <div><label for="early_leave_tolerance_minutes" class="block text-sm font-medium text-gray-700">Toleransi Pulang Cepat (menit) <span class="field-requirement is-required" aria-label="Wajib diisi">*</span></label><input id="early_leave_tolerance_minutes" name="early_leave_tolerance_minutes" type="number" min="0" max="240" value="{{ old('early_leave_tolerance_minutes', $shift->early_leave_tolerance_minutes ?? 0) }}" required class="mt-2 block w-full rounded-md border border-gray-300 px-3 py-2.5 text-sm shadow-xs outline-none focus:border-primary focus:ring-2 focus:ring-primary/20">@error('early_leave_tolerance_minutes')<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror</div>
        <label class="flex items-end gap-2 text-sm font-medium text-gray-700"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $shift->is_active ?? true)) class="mb-3 size-4 rounded border-gray-300 text-primary focus:ring-primary"><span class="pb-2.5">Aktif</span></label>
    </div>

    <h3 class="mt-6 text-sm font-semibold text-gray-950">Aturan Lembur</h3>
    <div class="mt-3 grid grid-cols-1 gap-5 md:grid-cols-2">
        <div>
            <label for="overtime_starts_after_minutes" class="block text-sm font-medium text-gray-700">Lembur Dihitung Setelah (menit)</label>
            <input id="overtime_starts_after_minutes" name="overtime_starts_after_minutes" type="number" min="0" max="480" value="{{ old('overtime_starts_after_minutes', $shift->overtime_starts_after_minutes ?? 0) }}" class="mt-2 block w-full rounded-md border border-gray-300 px-3 py-2.5 text-sm shadow-xs outline-none focus:border-primary focus:ring-2 focus:ring-primary/20">
            <p class="mt-2 text-xs text-gray-500">Menit setelah jam pulang sebelum lembur mulai terhitung. Contoh: 30 = 30 menit pertama tidak dihitung lembur.</p>
            @error('overtime_starts_after_minutes')<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror
        </div>
        <div>
            <label for="overtime_min_minutes" class="block text-sm font-medium text-gray-700">Minimal Lembur Terhitung (menit)</label>
            <input id="overtime_min_minutes" name="overtime_min_minutes" type="number" min="0" max="480" value="{{ old('overtime_min_minutes', $shift->overtime_min_minutes ?? 0) }}" class="mt-2 block w-full rounded-md border border-gray-300 px-3 py-2.5 text-sm shadow-xs outline-none focus:border-primary focus:ring-2 focus:ring-primary/20">
            <p class="mt-2 text-xs text-gray-500">Jika total lembur di bawah nilai ini, dianggap 0. Contoh: 30 = lembur &lt; 30 menit tidak dihitung.</p>
            @error('overtime_min_minutes')<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror
        </div>
    </div>

    <p class="mt-4 rounded-md bg-gray-50 px-3 py-2 text-xs text-gray-500">Shift <span class="font-medium text-gray-700">lintas tengah malam</span> (mis. 22:00–06:00) terdeteksi otomatis dari jam selesai yang lebih awal dari jam mulai.</p>
</section>
