<section class="rounded-lg border border-gray-200 bg-white p-6 shadow-sm">
    <div class="grid grid-cols-1 gap-5 md:grid-cols-2">
        <div><label for="code" class="block text-sm font-medium text-gray-700">Kode <span class="field-requirement is-required" aria-label="Wajib diisi">*</span></label><input id="code" name="code" value="{{ old('code', $shift->code) }}" required class="mt-2 block w-full rounded-md border border-gray-300 px-3 py-2.5 text-sm shadow-xs outline-none focus:border-primary focus:ring-2 focus:ring-primary/20">@error('code')<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror</div>
        <div><label for="name" class="block text-sm font-medium text-gray-700">Nama Shift <span class="field-requirement is-required" aria-label="Wajib diisi">*</span></label><input id="name" name="name" value="{{ old('name', $shift->name) }}" required class="mt-2 block w-full rounded-md border border-gray-300 px-3 py-2.5 text-sm shadow-xs outline-none focus:border-primary focus:ring-2 focus:ring-primary/20">@error('name')<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror</div>
        <div><label for="start_time" class="block text-sm font-medium text-gray-700">Jam Mulai <span class="field-requirement is-required" aria-label="Wajib diisi">*</span></label><input id="start_time" name="start_time" type="time" value="{{ old('start_time', $shift->start_time ? str($shift->start_time)->substr(0, 5) : '') }}" required class="mt-2 block w-full rounded-md border border-gray-300 px-3 py-2.5 text-sm shadow-xs outline-none focus:border-primary focus:ring-2 focus:ring-primary/20">@error('start_time')<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror</div>
        <div><label for="end_time" class="block text-sm font-medium text-gray-700">Jam Selesai <span class="field-requirement is-required" aria-label="Wajib diisi">*</span></label><input id="end_time" name="end_time" type="time" value="{{ old('end_time', $shift->end_time ? str($shift->end_time)->substr(0, 5) : '') }}" required class="mt-2 block w-full rounded-md border border-gray-300 px-3 py-2.5 text-sm shadow-xs outline-none focus:border-primary focus:ring-2 focus:ring-primary/20">@error('end_time')<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror</div>
        <div><label for="break_minutes" class="block text-sm font-medium text-gray-700">Istirahat (menit) <span class="field-requirement is-required" aria-label="Wajib diisi">*</span></label><input id="break_minutes" name="break_minutes" type="number" min="0" max="480" value="{{ old('break_minutes', $shift->break_minutes ?? 60) }}" required class="mt-2 block w-full rounded-md border border-gray-300 px-3 py-2.5 text-sm shadow-xs outline-none focus:border-primary focus:ring-2 focus:ring-primary/20">@error('break_minutes')<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror</div>
        <label class="flex items-end gap-2 text-sm font-medium text-gray-700"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $shift->is_active ?? true)) class="mb-3 size-4 rounded border-gray-300 text-primary focus:ring-primary"><span class="pb-2.5">Aktif</span></label>
    </div>
</section>
