<?php

namespace App\Support;

use App\Models\Branch;
use App\Models\Employee;
use Carbon\CarbonInterface;

/**
 * The employee code, generated by the system and never typed by hand:
 *
 *     COK[bulan bergabung][tahun bergabung]-[kode lokasi][id karyawan]
 *     e.g. bergabung 05-07-2026, lokasi "HO", id 12  =>  COK0726-HO0012
 *
 * Because the id is part of it, the code can only be built once the employee row
 * exists — Employee generates it right after insert, and refreshes it whenever the
 * join date or the work location changes (see Employee::booted()).
 */
class EmployeeNumber
{
    public const PREFIX = 'COK';

    /**
     * Stand-in for employees whose branch has no code (or no branch at all), so the
     * code keeps its shape instead of collapsing into "COK0726-0012".
     */
    public const FALLBACK_BRANCH_CODE = 'XX';

    public static function for(Employee $employee): string
    {
        // Read the branch fresh: on an update the loaded relation may still be the
        // location the employee is being moved away from.
        $branchCode = $employee->branch_id
            ? Branch::query()->whereKey($employee->branch_id)->value('code')
            : null;

        return self::format($employee->join_date, $branchCode, $employee->id);
    }

    public static function format(?CarbonInterface $joinDate, ?string $branchCode, int $employeeId): string
    {
        return sprintf(
            '%s%s-%s%04d',
            self::PREFIX,
            ($joinDate ?? now())->format('my'),
            self::branchCode($branchCode),
            $employeeId,
        );
    }

    /**
     * Branch codes are free text ("SBY-OFC-01"), so strip anything that would blur
     * the boundary between the location and the id.
     */
    public static function branchCode(?string $code): string
    {
        $clean = strtoupper(preg_replace('/[^A-Za-z0-9]/', '', (string) $code));

        return $clean !== '' ? $clean : self::FALLBACK_BRANCH_CODE;
    }
}
