<?php

namespace App\Models;

use App\Support\EmployeeNumber;
use Carbon\CarbonInterface;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class Employee extends Model
{
    /**
     * employee_number is deliberately absent: it is generated by the system (see
     * booted() / EmployeeNumber) and can never be set from a form or an import.
     *
     * @var list<string>
     */
    protected $fillable = [
        'branch_id',
        'user_id',
        'department_id',
        'job_position_id',
        'manager_id',
        'photo_path',
        'full_name',
        'email',
        'phone',
        'identity_number',
        'birth_date',
        'join_date',
        'employment_status',
        'follows_office_hours',
        'office_pattern_id',
        'exit_reason',
        'exit_date',
        'exit_notes',
        'address',
        'motto',
    ];

    /**
     * Employment status is binary: a person either works here (Aktif) or has left
     * (Nonaktif). Choosing Nonaktif on the form runs the exit flow (reason + date).
     */
    public const EMPLOYMENT_STATUS_LABELS = [
        'active' => 'Aktif',
        'inactive' => 'Nonaktif',
    ];

    public const EXIT_REASON_LABELS = [
        'resigned' => 'Mengundurkan Diri',
        'terminated' => 'PHK',
        'contract_ended' => 'Kontrak Berakhir',
        'retired' => 'Pensiun',
        'deceased' => 'Meninggal Dunia',
        'mutual_agreement' => 'Kesepakatan Bersama',
        'absent_without_notice' => 'Mangkir',
        'layoff' => 'Efisiensi / Restrukturisasi',
        'other' => 'Lainnya',
    ];

    /**
     * The employee code embeds the id, the join month and the branch code, so it is
     * written right after insert and refreshed whenever one of those changes.
     */
    protected static function booted(): void
    {
        static::created(function (Employee $employee): void {
            $employee->syncEmployeeNumber();
            $employee->ensureHomeDepartmentLinked();
        });

        static::updated(function (Employee $employee): void {
            if ($employee->wasChanged(['join_date', 'branch_id'])) {
                $employee->syncEmployeeNumber();
            }

            if ($employee->wasChanged('department_id')) {
                $employee->ensureHomeDepartmentLinked();
            }
        });
    }

    /**
     * Keep the home division present in the pivot, so an employee created/imported
     * with only department_id (no explicit multi-division sync) still resolves its
     * full division set from one place.
     */
    public function ensureHomeDepartmentLinked(): void
    {
        if ($this->department_id) {
            $this->departments()->syncWithoutDetaching([$this->department_id]);
        }
    }

    public function syncEmployeeNumber(): void
    {
        $number = EmployeeNumber::for($this);

        if ($this->employee_number !== $number) {
            // Quietly: this is a derived value, not an edit worth re-firing events for.
            $this->forceFill(['employee_number' => $number])->saveQuietly();
        }
    }

    public function branch(): BelongsTo
    {
        return $this->belongsTo(Branch::class);
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /** The employee's "home" division — the one their job position belongs to. */
    public function department(): BelongsTo
    {
        return $this->belongsTo(Department::class);
    }

    /**
     * Every division the employee belongs to (all equal). The home department_id is
     * always one of them; extra divisions are added on top. Reads that need the full
     * set (scoping, shift swap, filters) use this.
     */
    public function departments(): BelongsToMany
    {
        return $this->belongsToMany(Department::class, 'department_employee')->withTimestamps();
    }

    /**
     * @return list<int>
     */
    public function departmentIds(): array
    {
        $ids = $this->relationLoaded('departments')
            ? $this->departments->pluck('id')->all()
            : $this->departments()->pluck('departments.id')->all();

        // The home division is always a member, even before the pivot is synced.
        if ($this->department_id && ! in_array($this->department_id, $ids, true)) {
            $ids[] = $this->department_id;
        }

        return $ids;
    }

    public function jobPosition(): BelongsTo
    {
        return $this->belongsTo(JobPosition::class);
    }

    public function manager(): BelongsTo
    {
        return $this->belongsTo(Employee::class, 'manager_id');
    }

    public function subordinates(): HasMany
    {
        return $this->hasMany(Employee::class, 'manager_id');
    }

    public function leaveRequests(): HasMany
    {
        return $this->hasMany(LeaveRequest::class);
    }

    public function scheduleAssignments(): HasMany
    {
        return $this->hasMany(ScheduleAssignment::class);
    }

    public function schedules(): HasMany
    {
        return $this->hasMany(EmployeeSchedule::class);
    }

    /**
     * Pola jam kantor yang diikuti karyawan ini bila follows_office_hours menyala.
     * Null berarti ikut pola default global — lihat DefaultOfficeSchedule.
     */
    public function officePattern(): BelongsTo
    {
        // Terarsip pun tetap terbaca — sama alasannya dengan ScheduleAssignment::pattern().
        return $this->belongsTo(SchedulePattern::class, 'office_pattern_id')->withTrashed();
    }

    public function attendances(): HasMany
    {
        return $this->hasMany(Attendance::class);
    }

    public function deviceMappings(): HasMany
    {
        return $this->hasMany(EmployeeDevice::class);
    }

    public function punches(): HasMany
    {
        return $this->hasMany(AttendancePunch::class);
    }

    public function attendanceCorrections(): HasMany
    {
        return $this->hasMany(AttendanceCorrection::class);
    }

    public function overtimeApprovals(): HasMany
    {
        return $this->hasMany(OvertimeApproval::class);
    }

    public function swapRequests(): HasMany
    {
        return $this->hasMany(ShiftSwapRequest::class, 'requester_id');
    }

    public function swapRequestsAsPartner(): HasMany
    {
        return $this->hasMany(ShiftSwapRequest::class, 'partner_id');
    }

    /**
     * The employee's fingerprint-machine PIN (the global mapping, i.e. one that
     * applies to any device). Managed from the employee form for convenience.
     */
    protected function machineUserId(): Attribute
    {
        return Attribute::get(
            fn () => $this->deviceMappings()->whereNull('device_id')->value('machine_user_id'),
        );
    }

    /** Seluruh masa pegang aset karyawan ini, yang berjalan maupun yang sudah lewat. */
    public function assetAssignments(): HasMany
    {
        return $this->hasMany(AssetAssignment::class);
    }

    /** Aset yang masih ada di tangannya — dipakai penjaga proses keluar. */
    public function openAssetAssignments(): HasMany
    {
        return $this->assetAssignments()->whereNull('returned_at');
    }

    /** Berapa aset perusahaan yang masih ada di tangannya. */
    public function openAssetCount(): int
    {
        return $this->openAssetAssignments()->count();
    }

    public function contracts(): HasMany
    {
        return $this->hasMany(EmployeeContract::class);
    }

    public function events(): HasMany
    {
        return $this->hasMany(EmployeeEvent::class);
    }

    public function leaveBalances(): HasMany
    {
        return $this->hasMany(LeaveBalance::class);
    }

    public function currentContract(): HasOne
    {
        return $this->hasOne(EmployeeContract::class)
            ->where('status', 'active')
            ->latestOfMany('start_date');
    }

    /**
     * The most recent contract regardless of status — used to show contract info
     * (incl. its status) even for employees who have exited (no active contract).
     */
    public function latestContract(): HasOne
    {
        return $this->hasOne(EmployeeContract::class)->latestOfMany('start_date');
    }

    /**
     * The contract the edit form reads and writes: the active one when there is one,
     * otherwise the most recent (selesai/kedaluwarsa/diperpanjang/dibatalkan). Only
     * five of the six statuses are "active", so keying off currentContract alone left
     * the contract fields blank — and saving then created a duplicate contract row
     * instead of editing the existing one.
     */
    public function editableContract(): ?EmployeeContract
    {
        return $this->currentContract ?? $this->latestContract;
    }

    /**
     * Rows that make an employee's record part of the operational history: deleting
     * the employee would cascade these away (attendance, leave, schedules, …), so
     * once any of them exists the record can only be exited, never deleted.
     *
     * @var list<string>
     */
    public const HISTORY_RELATIONS = [
        'attendances',
        'punches',
        'schedules',
        'leaveRequests',
        'attendanceCorrections',
        'overtimeApprovals',
        // Pernah memegang aset perusahaan adalah riwayat juga: barisnya menyimpan
        // siapa yang bertanggung jawab atas sebuah barang dan kapan.
        'assetAssignments',
    ];

    /** Flag every history relation in one query, so a list can hide "Hapus" per row. */
    public function scopeWithHistoryFlags(Builder $query): void
    {
        $query->withExists(self::HISTORY_RELATIONS);
    }

    public function hasOperationalHistory(): bool
    {
        foreach (self::HISTORY_RELATIONS as $relation) {
            $flag = str($relation)->snake()->toString().'_exists';

            if (array_key_exists($flag, $this->attributes)) {
                if ($this->attributes[$flag]) {
                    return true;
                }

                continue; // flagged by withHistoryFlags(): no need to query
            }

            if ($this->{$relation}()->exists()) {
                return true;
            }
        }

        return false;
    }

    /**
     * Narrow a query to the employees the given user is allowed to see: those in one
     * of their work locations AND one of their divisions (an empty list on an axis
     * means "semua" for that axis). Holding the bypass permission lifts the scope
     * entirely; having neither the bypass nor any scope means seeing nobody — the
     * scope has simply not been set up for that user yet, and failing closed is the
     * only safe reading.
     */
    public function scopeVisibleTo(Builder $query, User $user, string $bypassPermission = User::SCOPE_BYPASS_EMPLOYEES): void
    {
        if ($user->seesAllData($bypassPermission)) {
            return;
        }

        // "Batasi ke bawahan" menggantikan cakupan lokasi/divisi: pengguna hanya
        // melihat karyawan di bawah garis atasannya (berjenjang).
        if ($user->isLimitedToSubordinates()) {
            $ids = $user->subordinateEmployeeIds();
            $query->whereIn('id', $ids !== [] ? $ids : [0]);

            return;
        }

        $branchIds = $user->accessBranchIds();
        $departmentIds = $user->accessDepartmentIds();

        if ($branchIds === [] && $departmentIds === []) {
            $query->whereRaw('1 = 0');

            return;
        }

        if ($branchIds !== []) {
            $query->whereIn('branch_id', $branchIds);
        }

        if ($departmentIds !== []) {
            // Visible if ANY of the employee's divisions is in scope (union), not only
            // the home division.
            $query->where(function (Builder $query) use ($departmentIds): void {
                $query->whereIn('department_id', $departmentIds)
                    ->orWhereHas('departments', fn (Builder $q) => $q->whereIn('departments.id', $departmentIds));
            });
        }
    }

    public function isVisibleTo(User $user, string $bypassPermission = User::SCOPE_BYPASS_EMPLOYEES): bool
    {
        if ($user->seesAllData($bypassPermission)) {
            return true;
        }

        if ($user->isLimitedToSubordinates()) {
            return in_array($this->id, $user->subordinateEmployeeIds(), true);
        }

        $branchIds = $user->accessBranchIds();
        $departmentIds = $user->accessDepartmentIds();

        if ($branchIds === [] && $departmentIds === []) {
            return false;
        }

        $inBranch = $branchIds === [] || in_array($this->branch_id, $branchIds, true);
        $inDepartment = $departmentIds === [] || array_intersect($departmentIds, $this->departmentIds()) !== [];

        return $inBranch && $inDepartment;
    }

    public function scopeActive(Builder $query): void
    {
        $query->where('employment_status', 'active');
    }

    public function scopeByBranch(Builder $query, int|string|null $branchId): void
    {
        $query->when($branchId, fn (Builder $query) => $query->where('branch_id', $branchId));
    }

    public function scopeByDepartment(Builder $query, int|string|null $departmentId): void
    {
        // Match any employee who has this division (home or additional).
        $query->when($departmentId, fn (Builder $query) => $query->where(function (Builder $query) use ($departmentId): void {
            $query->where('department_id', $departmentId)
                ->orWhereHas('departments', fn (Builder $q) => $q->where('departments.id', $departmentId));
        }));
    }

    /**
     * Seluruh penyaring daftar karyawan dalam satu tempat, dipakai bersama oleh
     * tabelnya, kartu ringkasan di atasnya, dan export Excel.
     *
     * Dulu ketiganya menyusun kondisinya sendiri-sendiri, dan sudah mulai menyimpang:
     * export tidak pernah ikut menyaring "kontrak akan berakhir", sehingga file yang
     * diunduh berisi lebih banyak baris daripada yang tampil di layar.
     *
     * Kunci yang tidak dikenali diabaikan, jadi pemanggil boleh meneruskan seluruh
     * query string apa adanya.
     *
     * @param  array<string, mixed>  $filters
     */
    public function scopeMatchingFilters(Builder $query, array $filters): void
    {
        $value = fn (string $key) => $filters[$key] ?? null;

        $query
            ->byBranch($value('branch_id'))
            ->byDepartment($value('department_id'))
            ->when($value('job_position_id'), fn (Builder $q, $id) => $q->where('job_position_id', $id))
            // Role menempel pada akun login, bukan pada karyawan: karyawan tanpa akun
            // memang tidak pernah cocok dengan penyaring ini.
            ->when($value('role_id'), fn (Builder $q, $id) => $q->whereHas('user.roles', fn (Builder $r) => $r->where('roles.id', $id)))
            ->when($value('status'), fn (Builder $q, $status) => $q->where('employment_status', $status))
            ->when($value('exit_reason'), fn (Builder $q, $reason) => $q->where('exit_reason', $reason))
            ->when($value('contract') === 'expiring', fn (Builder $q) => $q->whereHas('contracts', fn ($c) => $c->expiringWithin(30)))
            ->when($value('office_hours') === 'yes', fn (Builder $q) => $q->where('follows_office_hours', true))
            ->when($value('office_hours') === 'no', fn (Builder $q) => $q->where('follows_office_hours', false))
            ->when($value('schedule') === 'none', fn (Builder $q) => $q->withoutScheduleThisMonth())
            ->when($value('search'), fn (Builder $q, string $search) => $q->where(fn (Builder $inner) => $inner
                ->where('employee_number', 'like', "%{$search}%")
                ->orWhere('full_name', 'like', "%{$search}%")
                ->orWhere('email', 'like', "%{$search}%")));
    }

    /**
     * Karyawan yang belum punya satu pun baris roster pada bulan berjalan.
     *
     * Karyawan bertanda "ikut jam kantor" sengaja dikeluarkan: jadwal mereka
     * diturunkan dari pola dan memang tidak pernah dimaterialisasi menjadi baris
     * roster, jadi tanpa pengecualian ini mereka semua akan salah tampil sebagai
     * belum terjadwal. Aturannya sama persis dengan layar Penjadwalan › Belum
     * Terjadwal (mode bulanan), supaya kedua halaman tidak pernah berbeda jawaban.
     */
    public function scopeWithoutScheduleThisMonth(Builder $query): void
    {
        $from = now()->startOfMonth()->toDateString();
        $to = now()->endOfMonth()->toDateString();

        $query->where('follows_office_hours', false)
            ->whereDoesntHave('schedules', fn (Builder $q) => $q->whereBetween('work_date', [$from, $to]));
    }

    public function getContractTenureAttribute(): ?string
    {
        $contract = $this->currentContract;

        if (! $contract?->start_date) {
            return null;
        }

        return $contract->start_date->diffForHumans($contract->end_date ?? now(), true);
    }

    public function getRemainingContractDaysAttribute(): ?int
    {
        $endDate = $this->currentContract?->end_date;

        if (! $endDate) {
            return null;
        }

        return now()->startOfDay()->diffInDays($endDate, false);
    }

    public function getPhotoUrlAttribute(): ?string
    {
        return $this->photo_path ? Storage::disk('public')->url($this->photo_path) : null;
    }

    /**
     * Foto yang siap ditampilkan: foto karyawan bila ada, selain itu memakai
     * logo perusahaan sebagai gambar default.
     */
    public function getPhotoDisplayUrlAttribute(): string
    {
        return $this->photo_url ?? asset('img/company-logo.svg');
    }

    /**
     * Status kepegawaian orangnya: "Aktif" atau "Nonaktif". Menjawab satu pertanyaan
     * saja — apakah orang ini masih karyawan? Sengaja terpisah dari status kontrak,
     * karena seseorang bisa tetap aktif walau kontraknya sudah lewat tanggal.
     *
     * Dua accessor "status" lain di kelas ini menjawab hal yang berbeda:
     * - hr_status_label      : status kepegawaian DIGABUNG kondisi kontraknya
     * - contract_needs_attention : kontraknya lewat tanggal dan menunggu keputusan HR
     */
    public function getEmploymentStatusLabelAttribute(): string
    {
        return self::employmentStatusLabels()[$this->employment_status] ?? str($this->employment_status)->headline()->toString();
    }

    /** Warna lencana untuk employment_status_label. */
    public function getEmploymentStatusToneAttribute(): string
    {
        return match ($this->employment_status) {
            'active' => 'success',
            'inactive' => 'danger',
            default => 'neutral',
        };
    }

    public function getExitReasonLabelAttribute(): ?string
    {
        if (! $this->exit_reason) {
            return null;
        }

        return self::exitReasonLabels()[$this->exit_reason] ?? str($this->exit_reason)->headline()->toString();
    }

    public function getHrStatusLabelAttribute(): string
    {
        if ($this->isInactive()) {
            return trim('Tidak Aktif - '.($this->exit_reason_label ?? 'Alasan belum diisi'));
        }

        $status = $this->employment_status_label;
        $contract = $this->currentContract;

        if (! $contract) {
            return "{$status} - Belum ada kontrak aktif";
        }

        if ($contract->end_date === null) {
            return "{$status} - {$contract->contract_type} tanpa batas waktu";
        }

        $remainingDays = $this->remaining_contract_days;

        if ($remainingDays !== null && $remainingDays < 0) {
            return "{$status} - Kontrak berakhir ".abs($remainingDays).' hari lalu';
        }

        if ($remainingDays !== null && $remainingDays <= 30) {
            return "{$status} - Kontrak habis {$remainingDays} hari lagi";
        }

        return "{$status} - {$contract->contract_type} sampai ".$contract->end_date->format('d M Y');
    }

    public function isInactive(): bool
    {
        return $this->employment_status === 'inactive';
    }

    /**
     * Append an entry to the employee's work-history timeline. The causer defaults
     * to the authenticated user (null for background/console actions).
     *
     * @param  array<string, mixed>  $properties
     */
    public function recordEvent(string $type, ?string $description = null, ?CarbonInterface $occurredAt = null, array $properties = []): EmployeeEvent
    {
        return $this->events()->create([
            'type' => $type,
            'description' => $description,
            'occurred_at' => $occurredAt ?? now(),
            'causer_id' => Auth::id(),
            'properties' => $properties === [] ? null : $properties,
        ]);
    }

    /**
     * Mark the employee as exited (nonaktif) in one place: employment record, the
     * current contract, and the login account. Used by the manual resign flow, the
     * automatic "contract expired" deactivation, and the inline exit during edit.
     *
     * @param  bool  $syncContract  When false, the caller has already set the contract
     *                              state (e.g. the edit form), so we leave it untouched.
     */
    public function markAsExited(string $reason, CarbonInterface $exitDate, ?string $notes = null, bool $syncContract = true): void
    {
        $this->forceFill([
            'employment_status' => 'inactive',
            'exit_reason' => $reason,
            'exit_date' => $exitDate,
            'exit_notes' => $notes,
        ])->save();

        if ($syncContract && $this->currentContract) {
            $this->currentContract->forceFill([
                'end_date' => $exitDate,
                'status' => $reason === 'contract_ended' ? 'completed' : 'ended_early',
            ])->save();
        }

        if ($this->user) {
            $this->user->forceFill(['is_active' => false])->save();
            DB::table('sessions')->where('user_id', $this->user->id)->delete();
        }
    }

    /**
     * Bring an employee back to active. Exit details are cleared (the timeline keeps
     * the history) and the login account is re-enabled.
     */
    public function reactivate(): void
    {
        $this->forceFill([
            'employment_status' => 'active',
            'exit_reason' => null,
            'exit_date' => null,
            'exit_notes' => null,
        ])->save();

        if ($this->user) {
            $this->user->forceFill(['is_active' => true])->save();
        }
    }

    /**
     * The employee is still active, but their current contract period has already
     * lapsed and nobody has renewed it or processed the exit yet. This is the
     * situation that needs an explicit HR decision (renew vs. exit).
     */
    public function getContractNeedsAttentionAttribute(): bool
    {
        return ! $this->isInactive() && (bool) $this->currentContract?->is_lapsed;
    }

    /**
     * @return array<string, string>
     */
    public static function employmentStatusLabels(): array
    {
        return self::EMPLOYMENT_STATUS_LABELS;
    }

    /**
     * @return array<string, string>
     */
    public static function exitReasonLabels(): array
    {
        return self::EXIT_REASON_LABELS;
    }

    protected function casts(): array
    {
        return [
            'birth_date' => 'date',
            'join_date' => 'date',
            'exit_date' => 'date',
            'follows_office_hours' => 'boolean',
        ];
    }
}
